version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU

install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: VkMusic.sln
  parallel: true
  verbosity: minimal
  
before_build:
  - nuget restore VkMusic.sln
